### ISSUE TITLE
Add testing, please

### ISSUE THREAD

**Issue by treeowl** [dagit/logict-sequence#2]

**Comment by dagit** [comment]
Currently all my testing has been checking that existing code I've written in `LogicT` does the "correct" thing but along the way I discovered the `MonadPlus` definition from the paper's sources was incorrect. So I definitely agree we need some proper tests.

**Comment by dagit** [comment]
I got as far as getting an empty test module working with CI today. I know there's a lot of options in this space, but I chose hspec and hedgehog as I've had pretty good experiences with both in the past.

**Comment by treeowl** [comment]
I will fix through myself, but off the top of your head do you know if `hedgehog-fn` has special support for generating *polymorphic* functions (natural transformations in **Hask**)?

**Comment by dagit** [comment]
Sorry, I've never even heard of that package until now.

**Comment by treeowl** [comment]
It looks like the answer is no, sadly, which means the hoisting functions will probably just get manually constructed function arguments. I was hoping to avoid that!

**Comment by treeowl** [comment]
Oh, this is still open. Not any more! There's another ticket for plugging the gaps.
