### ISSUE TITLE
Add Foldable and Traversable

### ISSUE THREAD

**Issue by treeowl** [dagit/logict-sequence#44]
For arbitrary `Foldable` and `Traversable` underlying monads, there are a couple reasonable options, so we might not want to commit. However, `FlexibleInstances` lets us write

```haskell
instance Foldable (SeqT Identity) where ...
instance Traversable (SeqT Identity) where ...
```

without further commitments, so maybe we should start there.

**Comment by dagit** [comment]
Have you seen how `LogicT` deals with this? They use overlappable and overlapping instances. I've kind of been ignoring it, but it's probably a good thing to include some sort of `Foldable/Traversable` support. Perhaps in the `Compat` module if it's "weird".

**Comment by treeowl** [comment]
They do that for performance. I'm not sure what traversal order they use, since the CPS stuff is confusing.
